INSERT INTO genre (name) VALUES ('Комедия') ON CONFLICT DO NOTHING;
INSERT INTO genre (name) VALUES ('Драма') ON CONFLICT DO NOTHING;
INSERT INTO genre (name) VALUES ('Мультфильм') ON CONFLICT DO NOTHING;
INSERT INTO genre (name) VALUES ('Триллер') ON CONFLICT DO NOTHING;
INSERT INTO genre (name) VALUES ('Документальный') ON CONFLICT DO NOTHING;
INSERT INTO genre (name) VALUES ('Боевик') ON CONFLICT DO NOTHING;

INSERT INTO mpa (name) VALUES ('G') ON CONFLICT DO NOTHING;
INSERT INTO mpa (name) VALUES ('PG') ON CONFLICT DO NOTHING;
INSERT INTO mpa (name) VALUES ('PG-13') ON CONFLICT DO NOTHING;
INSERT INTO mpa (name) VALUES ('R') ON CONFLICT DO NOTHING;
INSERT INTO mpa (name) VALUES ('NC-17') ON CONFLICT DO NOTHING;

INSERT INTO friendship_status (name) VALUES ('Запрос отправлен') ON CONFLICT DO NOTHING;
INSERT INTO friendship_status (name) VALUES ('Подтверждена') ON CONFLICT DO NOTHING;